/*
 * Strava API v3
 *
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;

use crate::apis::ResponseContent;
use super::{Error, configuration};

/// struct for passing parameters to the method [`explore_segments`]
#[derive(Clone, Debug, Default)]
pub struct ExploreSegmentsParams {
    /// The latitude and longitude for two points describing a rectangular boundary for the search: [southwest corner latitutde, southwest corner longitude, northeast corner latitude, northeast corner longitude]
    pub bounds: Vec<f32>,
    /// Desired activity type.
    pub activity_type: Option<String>,
    /// The minimum climbing category.
    pub min_cat: Option<i32>,
    /// The maximum climbing category.
    pub max_cat: Option<i32>
}

/// struct for passing parameters to the method [`get_logged_in_athlete_starred_segments`]
#[derive(Clone, Debug, Default)]
pub struct GetLoggedInAthleteStarredSegmentsParams {
    /// Page number. Defaults to 1.
    pub page: Option<i32>,
    /// Number of items per page. Defaults to 30.
    pub per_page: Option<i32>
}

/// struct for passing parameters to the method [`get_segment_by_id`]
#[derive(Clone, Debug, Default)]
pub struct GetSegmentByIdParams {
    /// The identifier of the segment.
    pub id: i64
}

/// struct for passing parameters to the method [`star_segment`]
#[derive(Clone, Debug, Default)]
pub struct StarSegmentParams {
    /// The identifier of the segment to star.
    pub id: i64,
    /// If true, star the segment; if false, unstar the segment.
    pub starred: bool
}


/// struct for typed successes of method [`explore_segments`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ExploreSegmentsSuccess {
    Status200(crate::models::ExplorerResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed successes of method [`get_logged_in_athlete_starred_segments`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetLoggedInAthleteStarredSegmentsSuccess {
    Status200(Vec<crate::models::SummarySegment>),
    UnknownValue(serde_json::Value),
}

/// struct for typed successes of method [`get_segment_by_id`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetSegmentByIdSuccess {
    Status200(crate::models::DetailedSegment),
    UnknownValue(serde_json::Value),
}

/// struct for typed successes of method [`star_segment`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum StarSegmentSuccess {
    Status200(crate::models::DetailedSegment),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`explore_segments`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ExploreSegmentsError {
    DefaultResponse(crate::models::Fault),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_logged_in_athlete_starred_segments`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetLoggedInAthleteStarredSegmentsError {
    DefaultResponse(crate::models::Fault),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`get_segment_by_id`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetSegmentByIdError {
    DefaultResponse(crate::models::Fault),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`star_segment`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum StarSegmentError {
    DefaultResponse(crate::models::Fault),
    UnknownValue(serde_json::Value),
}


/// Returns the top 10 segments matching a specified query.
pub async fn explore_segments(configuration: &configuration::Configuration, params: ExploreSegmentsParams) -> Result<ResponseContent<ExploreSegmentsSuccess>, Error<ExploreSegmentsError>> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let bounds = params.bounds;
    let activity_type = params.activity_type;
    let min_cat = params.min_cat;
    let max_cat = params.max_cat;


    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/segments/explore", local_var_configuration.base_path);
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    local_var_req_builder = local_var_req_builder.query(&[("bounds", &bounds.into_iter().map(|p| p.to_string()).collect::<Vec<String>>().join(",").to_string())]);
    if let Some(ref local_var_str) = activity_type {
        local_var_req_builder = local_var_req_builder.query(&[("activity_type", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = min_cat {
        local_var_req_builder = local_var_req_builder.query(&[("min_cat", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = max_cat {
        local_var_req_builder = local_var_req_builder.query(&[("max_cat", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        let local_var_entity: Option<ExploreSegmentsSuccess> = serde_json::from_str(&local_var_content).ok();
        let local_var_result = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Ok(local_var_result)
    } else {
        let local_var_entity: Option<ExploreSegmentsError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

/// List of the authenticated athlete's starred segments. Private segments are filtered out unless requested by a token with read_all scope.
pub async fn get_logged_in_athlete_starred_segments(configuration: &configuration::Configuration, params: GetLoggedInAthleteStarredSegmentsParams) -> Result<ResponseContent<GetLoggedInAthleteStarredSegmentsSuccess>, Error<GetLoggedInAthleteStarredSegmentsError>> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let page = params.page;
    let per_page = params.per_page;


    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/segments/starred", local_var_configuration.base_path);
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    if let Some(ref local_var_str) = page {
        local_var_req_builder = local_var_req_builder.query(&[("page", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_str) = per_page {
        local_var_req_builder = local_var_req_builder.query(&[("per_page", &local_var_str.to_string())]);
    }
    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        let local_var_entity: Option<GetLoggedInAthleteStarredSegmentsSuccess> = serde_json::from_str(&local_var_content).ok();
        let local_var_result = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Ok(local_var_result)
    } else {
        let local_var_entity: Option<GetLoggedInAthleteStarredSegmentsError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

/// Returns the specified segment. read_all scope required in order to retrieve athlete-specific segment information, or to retrieve private segments.
pub async fn get_segment_by_id(configuration: &configuration::Configuration, params: GetSegmentByIdParams) -> Result<ResponseContent<GetSegmentByIdSuccess>, Error<GetSegmentByIdError>> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let id = params.id;


    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/segments/{id}", local_var_configuration.base_path, id=id);
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        let local_var_entity: Option<GetSegmentByIdSuccess> = serde_json::from_str(&local_var_content).ok();
        let local_var_result = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Ok(local_var_result)
    } else {
        let local_var_entity: Option<GetSegmentByIdError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

/// Stars/Unstars the given segment for the authenticated athlete. Requires profile:write scope.
pub async fn star_segment(configuration: &configuration::Configuration, params: StarSegmentParams) -> Result<ResponseContent<StarSegmentSuccess>, Error<StarSegmentError>> {
    let local_var_configuration = configuration;

    // unbox the parameters
    let id = params.id;
    let starred = params.starred;


    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/segments/{id}/starred", local_var_configuration.base_path, id=id);
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::PUT, local_var_uri_str.as_str());

    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_token) = local_var_configuration.oauth_access_token {
        local_var_req_builder = local_var_req_builder.bearer_auth(local_var_token.to_owned());
    };
    let mut local_var_form = reqwest::multipart::Form::new();
    local_var_form = local_var_form.text("starred", starred.to_string());
    local_var_req_builder = local_var_req_builder.multipart(local_var_form);

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        let local_var_entity: Option<StarSegmentSuccess> = serde_json::from_str(&local_var_content).ok();
        let local_var_result = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Ok(local_var_result)
    } else {
        let local_var_entity: Option<StarSegmentError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

