/*
 * Strava API v3
 *
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ActivityType : An enumeration of the types an activity may have.

/// An enumeration of the types an activity may have.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ActivityType {
    #[serde(rename = "AlpineSki")]
    AlpineSki,
    #[serde(rename = "BackcountrySki")]
    BackcountrySki,
    #[serde(rename = "Canoeing")]
    Canoeing,
    #[serde(rename = "Crossfit")]
    Crossfit,
    #[serde(rename = "EBikeRide")]
    EBikeRide,
    #[serde(rename = "Elliptical")]
    Elliptical,
    #[serde(rename = "Golf")]
    Golf,
    #[serde(rename = "Handcycle")]
    Handcycle,
    #[serde(rename = "Hike")]
    Hike,
    #[serde(rename = "IceSkate")]
    IceSkate,
    #[serde(rename = "InlineSkate")]
    InlineSkate,
    #[serde(rename = "Kayaking")]
    Kayaking,
    #[serde(rename = "Kitesurf")]
    Kitesurf,
    #[serde(rename = "NordicSki")]
    NordicSki,
    #[serde(rename = "Ride")]
    Ride,
    #[serde(rename = "RockClimbing")]
    RockClimbing,
    #[serde(rename = "RollerSki")]
    RollerSki,
    #[serde(rename = "Rowing")]
    Rowing,
    #[serde(rename = "Run")]
    Run,
    #[serde(rename = "Sail")]
    Sail,
    #[serde(rename = "Skateboard")]
    Skateboard,
    #[serde(rename = "Snowboard")]
    Snowboard,
    #[serde(rename = "Snowshoe")]
    Snowshoe,
    #[serde(rename = "Soccer")]
    Soccer,
    #[serde(rename = "StairStepper")]
    StairStepper,
    #[serde(rename = "StandUpPaddling")]
    StandUpPaddling,
    #[serde(rename = "Surfing")]
    Surfing,
    #[serde(rename = "Swim")]
    Swim,
    #[serde(rename = "Velomobile")]
    Velomobile,
    #[serde(rename = "VirtualRide")]
    VirtualRide,
    #[serde(rename = "VirtualRun")]
    VirtualRun,
    #[serde(rename = "Walk")]
    Walk,
    #[serde(rename = "WeightTraining")]
    WeightTraining,
    #[serde(rename = "Wheelchair")]
    Wheelchair,
    #[serde(rename = "Windsurf")]
    Windsurf,
    #[serde(rename = "Workout")]
    Workout,
    #[serde(rename = "Yoga")]
    Yoga,

}

impl ToString for ActivityType {
    fn to_string(&self) -> String {
        match self {
            Self::AlpineSki => String::from("AlpineSki"),
            Self::BackcountrySki => String::from("BackcountrySki"),
            Self::Canoeing => String::from("Canoeing"),
            Self::Crossfit => String::from("Crossfit"),
            Self::EBikeRide => String::from("EBikeRide"),
            Self::Elliptical => String::from("Elliptical"),
            Self::Golf => String::from("Golf"),
            Self::Handcycle => String::from("Handcycle"),
            Self::Hike => String::from("Hike"),
            Self::IceSkate => String::from("IceSkate"),
            Self::InlineSkate => String::from("InlineSkate"),
            Self::Kayaking => String::from("Kayaking"),
            Self::Kitesurf => String::from("Kitesurf"),
            Self::NordicSki => String::from("NordicSki"),
            Self::Ride => String::from("Ride"),
            Self::RockClimbing => String::from("RockClimbing"),
            Self::RollerSki => String::from("RollerSki"),
            Self::Rowing => String::from("Rowing"),
            Self::Run => String::from("Run"),
            Self::Sail => String::from("Sail"),
            Self::Skateboard => String::from("Skateboard"),
            Self::Snowboard => String::from("Snowboard"),
            Self::Snowshoe => String::from("Snowshoe"),
            Self::Soccer => String::from("Soccer"),
            Self::StairStepper => String::from("StairStepper"),
            Self::StandUpPaddling => String::from("StandUpPaddling"),
            Self::Surfing => String::from("Surfing"),
            Self::Swim => String::from("Swim"),
            Self::Velomobile => String::from("Velomobile"),
            Self::VirtualRide => String::from("VirtualRide"),
            Self::VirtualRun => String::from("VirtualRun"),
            Self::Walk => String::from("Walk"),
            Self::WeightTraining => String::from("WeightTraining"),
            Self::Wheelchair => String::from("Wheelchair"),
            Self::Windsurf => String::from("Windsurf"),
            Self::Workout => String::from("Workout"),
            Self::Yoga => String::from("Yoga"),
        }
    }
}

impl Default for ActivityType {
    fn default() -> ActivityType {
        Self::AlpineSki
    }
}




