/*
 * Strava API v3
 *
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SummaryPrSegmentEffort {
    /// The unique identifier of the activity related to the PR effort.
    #[serde(rename = "pr_activity_id", skip_serializing_if = "Option::is_none")]
    pub pr_activity_id: Option<i64>,
    /// The elapsed time ot the PR effort.
    #[serde(rename = "pr_elapsed_time", skip_serializing_if = "Option::is_none")]
    pub pr_elapsed_time: Option<i32>,
    /// The time at which the PR effort was started.
    #[serde(rename = "pr_date", skip_serializing_if = "Option::is_none")]
    pub pr_date: Option<String>,
    /// Number of efforts by the authenticated athlete on this segment.
    #[serde(rename = "effort_count", skip_serializing_if = "Option::is_none")]
    pub effort_count: Option<i32>,
}

impl SummaryPrSegmentEffort {
    pub fn new() -> SummaryPrSegmentEffort {
        SummaryPrSegmentEffort {
            pr_activity_id: None,
            pr_elapsed_time: None,
            pr_date: None,
            effort_count: None,
        }
    }
}


