name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:

  build:
    name: ${{ matrix.make.name }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, macos-latest]
        rust: [stable]
        make:
          #- name: Clippy
          #  task: "check-clippy"
          #- name: Unit tests
          #  task: "build-all-test run-all-unit-test"
          #- name: Doc tests
          #  task: "run-all-doc-test"
          - name: Unit tests
            cmd: cargo test --verbose
        exclude:
          - os: macos-latest
            rust: stable
            make:
              name: Clippy  

    env:
      RUST_BACKTRACE: full
      RUSTV: ${{ matrix.rust }}

    steps:
      - name: Checkout sourcecode
        uses: actions/checkout@v2
      - name: Install Rust ${{ matrix.rust }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true
      - name: Cache
        uses: Swatinem/rust-cache@v1
        with:
          key: ${{ matrix.os }}-${{ matrix.rust }}
      - name: ${{ matrix.make.name }}
        run: ${{ matrix.make.cmd }}